### ISSUE TITLE
Studio crash when using python api

### ISSUE THREAD

**Issue by Paul-Wray** [libfive/libfive#499] opened 2022-04-26 11:23 UTC
### Description

Studio crashes with segfault under Python API when altering last component of vector.

To reproduce, input something like 

cube([0,0,0], [1,2,3])

Then delete the 3

- Operating system: OSX
Branch: master
Revision: f471c12

**Comment by mkeeter** [comment] 2022-04-26 12:55
This is not the latest commit to `master`, which is 53dec8359fb665c8df2684f5fdd2aea1ebbfbd5f. I believe this is #438, which is now fixed (and was not fixed in f471c12ea6766ed07cc99597423018ded8b238e7).  Please update your checkout and reopen if the issue is still reproducible.

**Closed by mkeeter** 2022-04-26 12:55 UTC

**Comment by Paul-Wray** [comment] 2022-04-27 05:32
I was using the prebuilt OSX app file on the website. Latest code works OK.
