### ISSUE TITLE
Scheme files not loading in Studio on MacOS 10.15

### ISSUE THREAD

**Issue by leokeba** [libfive/libfive#426] opened 2021-04-26 15:55 UTC
### Description

Wether it's loading script files through finder, or through file menu > open, nothing happens and I just get the default script. I can, however, directly paste the text from the file, and then it works like expected. Is there anything specific I can do to investigate further ?

### Versions

- Operating system: MacOS 10.15.7
- `libfive` commit hash: latest release, i get this from the "about" menu : a0b883a
  - Is this the latest commit to `master`?  no
- Qt version (if applicable): Don't know

### Additional Information

Edit : This only seems to affect with files using the Scheme syntax, Python script do not seem to suffer from the same bug. This is okay for me as I mostly intend to use python if all the features are exposed as well.

Thanks, and keep up the good work :)

**Comment by mkeeter** [comment] 2021-04-26 22:02
Looks like this is a dupe of #411 , so I'll rebuild a fresh app and update the website.

**Comment by mkeeter** [comment] 2021-04-26 22:19
Updated!

**Closed by mkeeter** 2021-04-26 22:19 UTC

**Comment by leokeba** [comment] 2021-04-26 22:20
Thanks a lot!
