### ISSUE TITLE
Cone with point at origin causes segfault in studio.

### ISSUE THREAD

**Issue by Paul-Wray** [libfive/libfive#179] opened 2018-06-19 12:24 UTC
### Description

(cone 1 1 [0 0 -1]) 
causes a segfault

### Versions
Update prebuilt version from the libfive site, which Matt updated a couple of days ago (no version info yet available via GUI).

The problem with Pyramid is fixed in this version, thanks. I had assumed this issue was the same assertion error, but I see now its a segfault.

**Comment by mkeeter** [comment] 2018-06-19 13:05
Confirmed, I'll check it out.

**Comment by mkeeter** [comment] 2018-06-19 13:11
(cones are the worst, by the way – the distance field at the tip goes haywire, with normals becoming invalid / `NaN`)

**Comment by mkeeter** [comment] 2018-06-26 12:37
This is caused by interval evaluation vs point evaluation behaving differently relative to `NaN`.

For example, the interval evaluation `[0 0.1] * [-inf -10]` yields `[-inf -0]`, when the bounds actually include `NaN`; doing point evaluation on the `NaN` corner gives a result that could disagree with the interval results, because `NaN` is inconvenient.

I'm still thinking about the best way to handle this without adding excessive cost to well-behaved models.

**Comment by mkeeter** [comment] 2018-06-28 23:32
This should be fixed now, with a more detailed explanation [here](https://github.com/libfive/libfive/issues/182#issuecomment-401203622).

**Closed by mkeeter** 2018-06-28 23:32 UTC
Labels: bug, kernel
